services:
  server:
    # image: 'amd64/nginx'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    platform: linux/amd64
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - '3000:9000'

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]

  npm:
    image: node:latest
    platform: linux/amd64
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
